# Generated by Django 3.1.5 on 2021-01-19 18:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(default='default.png', upload_to='images/')),
                ('bio', models.TextField(blank=True, default='My Bio', max_length=500)),
                ('following', models.ManyToManyField(blank=True, related_name='following', to=settings.AUTH_USER_MODEL)),
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='pics/')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('caption', models.CharField(blank=True, max_length=250)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(blank=True, null='True', on_delete=django.db.models.deletion.CASCADE, to='instaapp.profile')),
            ],
            options={
                'ordering': ['-date_posted'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('name', models.CharField(blank=True, max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('image', models.ForeignKey(blank=True, null='True', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='instaapp.image')),
                ('user', models.ForeignKey(blank=True, null='True', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='instaapp.profile')),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
    ]
